apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: je2i4d4me-java-springboot 
  janus-idp.io/tekton: je2i4d4me-java-springboot
  backstage.io/kubernetes-id: je2i4d4me-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: je2i4d4me-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml