apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: je2i4d4me-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/je2i4d4me-java-springboot-gitops